#!/bin/sh

base_lang="English"
target_langs="Japanese zh_TW"
target_nibs="MainMenu"

cd `dirname $0`

# update NIBFILE.Strings in ${base_lang}.lproj
for nib in $target_nibs; do
  nib_base="${base_lang}.lproj/${nib}"
  if [ \( ! -f "${nib_base}.strings" \) \
      -o "${nib_base}.nib" -nt "${nib_base}.strings" ]; then
    nibtool -8 -L "${nib_base}.nib" > "${nib_base}.strings"
  fi
done

# localize nib files if needed
for lang in $target_langs; do
  for nib in $target_nibs; do
    base_nib=${base_lang}.lproj/${nib}.nib
    target_nib=${lang}.lproj/${nib}.nib
    target_lstr=${lang}.lproj/${nib}.strings
    if [ \( $base_nib -nt $target_nib \) -o \
         \( $target_lstr -nt $target_nib \) ]; then
      nibtool -8 -d $target_lstr -W $target_nib $base_nib && \
          touch $target_nib
    fi
  done
done
